version: '3'
services:
  dnsmasq:
    build:
      context: .
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /opt/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
      - /opt/dnsmasq/hosts.dnsmasq:/etc/hosts.dnsmasq
    #privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
