version: '3'
services:

  app:
    build:
      context: app/
    volumes:
      - selfoss:/var/www/selfoss
      - /opt/selfoss/data:/var/www/selfoss/data
      - /opt/selfoss/config.ini:/var/www/selfoss/config.ini
    env_file:
      - /opt/selfoss/selfoss.env

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - selfoss:/var/www/selfoss
    depends_on:
      - app
    ports:
      - 3001:80
    restart: always

  db:
    image: mariadb
    volumes:
      - /opt/selfoss/db:/var/lib/mysql
    env_file:
      - /opt/selfoss/selfoss.env


volumes:
  selfoss:
