---
version: '3.4'

services:

  app:
    image: mayanedms/mayanedms
    ports:
      - "81:80"
    volumes:
      - type: volume
        source: mayan_settings
        target: /etc/mayan
      - type: bind
        source: /opt/mayan/files
        target: /var/lib/mayan
    env_file: /opt/mayan/.env
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - type: bind
        source: /opt/mayan/db
        target: /var/lib/postgresql/data
    env_file: /opt/mayan/.env

volumes:
  mayan_settings:
