---
version: '3'
services:
  gitea:
    image: gitea/gitea:1.11.3
    volumes:
      - "/srv/www/gitea:/data"
    networks:
      - nginx_backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.git.rule=Host(`git.xsteadfastx.org`)"
      - "traefik.http.routers.git.entrypoints=websecure"
      - "traefik.http.routers.git.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.git.LoadBalancer.server.Port=3000"
networks:
  nginx_backend:
    external: true
