---
version: '3'
services:

  db:
    # restart: always
    image: postgres:alpine
    volumes:
      - /opt/mastodon/db:/var/lib/postgresql/data

  redis:
    # restart: always
    image: redis:alpine

  web:
    build: ./mastodon/
    image: gargron/mastodon
    # restart: always
    env_file: /opt/mastodon/.env.production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - ./mastodon/public/assets:/mastodon/public/assets
      - ./mastodon/public/packs:/mastodon/public/packs
      - ./mastodon/public/system:/mastodon/public/system

  streaming:
    build: ./mastodon/
    image: gargron/mastodon
    # restart: always
    env_file: /opt/mastodon/.env.production
    command: npm run start
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    build: ./mastodon/
    image: gargron/mastodon
    # restart: always
    env_file: /opt/mastodon/.env.production
    command: bundle exec sidekiq -q default -q mailers -q pull -q push
    depends_on:
      - db
      - redis
    volumes:
      - ./mastodon/public/system:/mastodon/public/system
