version: '3'
services:
  bitlbee:
    build:
      context: bitlbee
    restart: always
    volumes:
      - "/opt/bitlbee/data/bitlbee:/etc/bitlbee"
      - "/opt/bitlbee/data/users:/var/lib/bitlbee"
    logging:
      options:
        max-size: 5m

networks:
  default:
    external:
      name: prosody_default
