version: '2'
services:
  bitlbee:
    build:
      context: bitlbee
    restart: always
    volumes:
      - "/opt/bitlbee/data/bitlbee:/etc/bitlbee"
      - "/opt/bitlbee/data/users:/var/lib/bitlbee"
    ports:
      - "127.0.0.1:6667:6667"
    external_links:
      - prosody_prosody_1:prosody

networks:
  default:
    external:
      name: prosody_default
