---
version: '3'
services:

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
      - "8448:8448"
    volumes:
      - /etc/nginx:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx:/var/log/nginx
      - /opt/synapse:/opt/synapse
      - /srv/www/letsencrypt:/srv/www/letsencrypt
      - /home/marv/Media:/srv/www/media:ro
    restart: on-failure
    networks:
      - nginx_backend
      - nginx_frontend

networks:
  nginx_frontend:
  nginx_backend:
    external: true
